# -*- coding: utf-8 -*-
"""Cópia de Cópia de ListaExercicio4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M9gx0Rywb_23OGFvjP9_6rb6FsllBcyj

# 📊 Projeto Final – Análise Contábil com Ajuste Econômico

Este projeto tem como objetivo integrar análise de dados contábeis de empresas com indicadores econômicos, utilizando Python, Pandas, Ipeadata e Streamlit.

1) Configure o título na barra do navegador, da página do projeto no Streamlit e descrição inicial do projeto (peso: 1,0)

- Título na barra (`page_title`): Lista de Exercícios 4
- Título da página (`header`): Projeto Final – Análise Contábil com Ajuste Econômico
- Descrição projeto (`write`): Este projeto tem como objetivo integrar análise de dados contábeis de empresas com indicadores econômicos, utilizando Python, Pandas, Ipeadata e Streamlit.
"""

page_title = "Lista de Exercícios 4"
header = "Projeto Final – Análise Contábil com Ajuste Econômico"
write = "Este projeto tem como objetivo integrar análise de dados contábeis de empresas com indicadores econômicos, utilizando Python, Pandas, Ipeadata e Streamlit."

"""2) Importe os dados do arquivo empresas_dados.csv utilizando pandas e apresente todas as linhas da df (peso: 1,0)

Dica: Utilize `head(len(df))`
"""

import pandas as pd
import streamlit as st

df = pd.read_csv("empresas_dados.csv", sep=";")


df.head(len(df))

"""3) Calcule os indicadores Margem Líquida e ROA e salve como novas coluna da df. Depois apresente os dois indicadores no mesmo gráfico de linhas, agrupado por Ano  (peso: 1,0)

- Margem Líquida = Lucro Líquido / Receita Líquida * 100
- ROA = Lucro Líquido / Ativo Total *  100
"""

margem_liquida = df["Lucro Líquido"] / df["Receita Líquida"] * 100
df["Margem Líquida"] = margem_liquida

roa = df["Lucro Líquido"] / df["Ativo Total"] * 100
df["ROA"] = roa

df_atualizada = df[["Empresa", "Ano", "Receita Líquida", "Lucro Líquido", "Ativo Total", "Setor", "UF", "Margem Líquida", "ROA"]]
df_atualizada

import matplotlib.pyplot as plt
df_margem_liquida = df_atualizada.groupby("Ano")["Margem Líquida"].mean()
df_roa = df_atualizada.groupby("Ano")["ROA"].mean()
plt.plot(df_margem_liquida, label="Margem Líquida")
plt.plot(df_roa, label="ROA")
plt.legend()
plt.xlabel("Ano")
plt.ylabel("Valor")
plt.title("Margem Líquida e ROA ao longo dos anos")
plt.show()

"""4) Utilize o pacote ipeadatapy e faça busca para encontrar o indicador que traga o IPCA, taxa de variação, em % e anual: (peso: 2,0)

- Baixe os dados no período de 2010 a 2024
- Altere o nome da coluna "YEAR" para "Ano"
- Altere o nome da coluna "VALUE ((% a.a.))" para "IPCA"
- Apresente a df para checar se tudo deu certo
"""



import ipeadatapy as ip

df1 = ip.timeseries("PRECOS_IPCAG")
df1 = df1.loc["2010":"2024"]
df1 = df1.rename(columns={"YEAR": "Ano", "VALUE ((% a.a.))": "IPCA"})

df1

"""5) Combine as duas df (Excel e IPEA) em uma nova df e calcule nova coluna chamada Receita Real (peso: 2,0)

- Utilize a função `pd.merge()` para unificar as duas df utiilizando a coluna Ano como conexão (chave primária) entre elas
- Crie nova coluna chamada Receita Real que será o resultado da Receita Líquida de cada ano deduzido o IPCA do ano: `Receita Real = Receitta Líquida - ( Receita Líquida * (IPCA/100) )`
- Apresente a nova df combinada

"""

df_combinada = pd.merge(df, df1, on="Ano")
df_combinada["Receita Real"] = df_combinada["Receita Líquida"] - (df_combinada["Receita Líquida"] * (df_combinada["IPCA"] / 100))
df_combinada

"""6) Crie gráfico de linha que apresente as variáveis Receita Líquida e Receita Real ao longo dos anos (no mesmo gráfico) (peso: 1,0)"""

import matplotlib.pyplot as plt

df_receita_liquida = df_combinada.groupby("Ano")["Receita Líquida"].mean()
df_receita_real = df_combinada.groupby("Ano")["Receita Real"].mean()

plt.plot(df_receita_liquida, label="Receita Líquida")
plt.plot(df_receita_real, label="Receita Real")
plt.xlabel("Ano")
plt.ylabel("Valor (médio)")
plt.title("Receita Líquida e Receita Real ao longo dos anos")
plt.legend()
plt.tight_layout()
plt.show()

"""7) Faça os ajustes necessários e leve este projeto para a web usando GitHub e Streamlit (peso: 2,0)

- Caça os ajustes necessários no projeto para ser publicado no Streamlit
- Crie novo repositório público no GitHub e leve os arquivos .py e .csv pra lá. Aproveite e crie o arquivo requirements.txt com os pacotes utilizados no projeto
- Crie novo projeto no Streamlit e associe ao repositório da lista
"""
